'Insert into Barrios(id_barrio, nombre) Values (1  , '1 DE MAYO'                                     )
'Insert into Barrios(id_barrio, nombre) Values (2  , '2 DE SEPTIEMBRE'                               )
'Insert into Barrios(id_barrio, nombre) Values (3  , '20 DE JUNIO'                                   )
'Insert into Barrios(id_barrio, nombre) Values (4  , '23 DE ABRIL'                                   )
'Insert into Barrios(id_barrio, nombre) Values (5  , '25 DE MAYO'                                    )
'Insert into Barrios(id_barrio, nombre) Values (6  , '4 DE FEBRERO'                                  )
'Insert into Barrios(id_barrio, nombre) Values (7  , 'ACHAVAL PENA'                                  )
'Insert into Barrios(id_barrio, nombre) Values (8  , 'ACOSTA'                                        )
'Insert into Barrios(id_barrio, nombre) Values (9  , 'AERONAUTICO - VILLA ZAPPELIN'                  )
'Insert into Barrios(id_barrio, nombre) Values (10 , 'AEROPUERTO'                                    )
'Insert into Barrios(id_barrio, nombre) Values (11 , 'AIRES DEL SUR'                                 )
'Insert into Barrios(id_barrio, nombre) Values (12 , 'ALBERDI'                                       )
'Insert into Barrios(id_barrio, nombre) Values (13 , 'ALBORADA NORTE'                                )
'Insert into Barrios(id_barrio, nombre) Values (14 , 'ALBORADA SUR'                                  )
'Insert into Barrios(id_barrio, nombre) Values (15 , 'ALEJANDRO CENTENO'                             )
'Insert into Barrios(id_barrio, nombre) Values (16 , 'ALMIRANTE BROWN'                               )
'Insert into Barrios(id_barrio, nombre) Values (17 , 'ALTA CORDOBA'                                  )
'Insert into Barrios(id_barrio, nombre) Values (18 , 'ALTAMIRA'                                      )
'Insert into Barrios(id_barrio, nombre) Values (19 , 'ALTO ALBERDI'                                  )
'Insert into Barrios(id_barrio, nombre) Values (20 , 'ALTO DE DON BOSCO'                             )
'Insert into Barrios(id_barrio, nombre) Values (21 , 'ALTO DE SANTA ANA'                             )
'Insert into Barrios(id_barrio, nombre) Values (22 , 'ALTO HERMOSO'                                  )
'Insert into Barrios(id_barrio, nombre) Values (23 , 'ALTO PALERMO'                                  )
'Insert into Barrios(id_barrio, nombre) Values (24 , 'ALTO VERDE'                                    )
'Insert into Barrios(id_barrio, nombre) Values (26 , 'ALTOS DE VELEZ SARSFIELD'                      )
'Insert into Barrios(id_barrio, nombre) Values (27 , 'ALTOS DE VILLA CABRERA'                        )
'Insert into Barrios(id_barrio, nombre) Values (28 , 'ALTOS SAN MARTIN'                              )
'Insert into Barrios(id_barrio, nombre) Values (29 , 'ALTOS SUD DE SAN VICENTE'                      )
'Insert into Barrios(id_barrio, nombre) Values (30 , 'AMEGHINO NORTE'                                )
'Insert into Barrios(id_barrio, nombre) Values (31 , 'AMEGHINO SUD'                                  )
'Insert into Barrios(id_barrio, nombre) Values (32 , 'AMPLIACION ALTAMIRA'                           )
'Insert into Barrios(id_barrio, nombre) Values (33 , 'AMPLIACION BENJAMIN MATIENZO'                  )
'Insert into Barrios(id_barrio, nombre) Values (34 , 'AMPLIACION CABO FARINA'                        )
'Insert into Barrios(id_barrio, nombre) Values (35 , 'AMPLIACION EMPALME'                            )
'Insert into Barrios(id_barrio, nombre) Values (36 , 'AMPLIACION GENERAL ARTIGAS'                    )
'Insert into Barrios(id_barrio, nombre) Values (37 , 'AMPLIACION JARDIN ESPINOSA'                    )
'Insert into Barrios(id_barrio, nombre) Values (38 , 'AMPLIACION JOSE IGNACIO DIAZ SECCION 2'        )
'Insert into Barrios(id_barrio, nombre) Values (39 , 'AMPLIACION JOSE IGNACIO DIAZ SECCION 3'        )
'Insert into Barrios(id_barrio, nombre) Values (40 , 'AMPLIACION KENNEDY'                            )
'Insert into Barrios(id_barrio, nombre) Values (41 , 'AMPLIACION LAS PALMAS'                         )
'Insert into Barrios(id_barrio, nombre) Values (42 , 'AMPLIACION LOS ALAMOS'                         )
'Insert into Barrios(id_barrio, nombre) Values (43 , 'AMPLIACION LOS PLATANOS'                       )
'Insert into Barrios(id_barrio, nombre) Values (44 , 'AMPLIACION PALMAR'                             )
'Insert into Barrios(id_barrio, nombre) Values (45 , 'AMPLIACION PANAMERICANO'                       )
'Insert into Barrios(id_barrio, nombre) Values (46 , 'AMPLIACION PARQUE SAN CARLOS'                  )
'Insert into Barrios(id_barrio, nombre) Values (47 , 'AMPLIACION POETA LUGONES'                      )
'Insert into Barrios(id_barrio, nombre) Values (48 , 'AMPLIACION PRIMERO DE MAYO'                    )
'Insert into Barrios(id_barrio, nombre) Values (49 , 'AMPLIACION PUEYRREDON'                         )
'Insert into Barrios(id_barrio, nombre) Values (50 , 'AMPLIACION RESIDENCIAL AMERICA'                )
'Insert into Barrios(id_barrio, nombre) Values (51 , 'AMPLIACION ROSEDAL'                            )
'Insert into Barrios(id_barrio, nombre) Values (52 , 'AMPLIACION SAN FERNANDO'                       )
'Insert into Barrios(id_barrio, nombre) Values (53 , 'AMPLIACION SAN PABLO'                          )
'Insert into Barrios(id_barrio, nombre) Values (54 , 'AMPLIACION URCA'                               )
'Insert into Barrios(id_barrio, nombre) Values (55 , 'AMPLIACION VELEZ SARSFIELD'                    )
'Insert into Barrios(id_barrio, nombre) Values (56 , 'ANA MARIA ZUMARAN'                             )
'Insert into Barrios(id_barrio, nombre) Values (57 , 'ANEXO LOS ALAMOS'                              )
'Insert into Barrios(id_barrio, nombre) Values (58 , 'APEADERO LA TABLADA'                           )
'Insert into Barrios(id_barrio, nombre) Values (59 , 'ARGUELLO'                                      )
'Insert into Barrios(id_barrio, nombre) Values (60 , 'ARGUELLO II'                                   )
'Insert into Barrios(id_barrio, nombre) Values (61 , 'ARGUELLO NORTE'                                )
'Insert into Barrios(id_barrio, nombre) Values (62 , 'ARTURO CAPDEVILA'                              )
'Insert into Barrios(id_barrio, nombre) Values (63 , 'ATE'                                           )
'Insert into Barrios(id_barrio, nombre) Values (64 , 'AVENIDA'                                       )
'Insert into Barrios(id_barrio, nombre) Values (65 , 'AYACUCHO'                                      )
'Insert into Barrios(id_barrio, nombre) Values (66 , 'BAJADA DE PIEDRA'                              )
'Insert into Barrios(id_barrio, nombre) Values (67 , 'BAJADA SAN ROQUE'                              )
'Insert into Barrios(id_barrio, nombre) Values (68 , 'BAJO GALAN'                                    )
'Insert into Barrios(id_barrio, nombre) Values (69 , 'BAJO GENERAL PAZ'                              )
'Insert into Barrios(id_barrio, nombre) Values (70 , 'BARRANCAS DEL SUR'                             )
'Insert into Barrios(id_barrio, nombre) Values (72 , 'BELLA VISTA'                                   )
'Insert into Barrios(id_barrio, nombre) Values (73 , 'BELLA VISTA OESTE'                             )
'Insert into Barrios(id_barrio, nombre) Values (74 , 'BETANIA'                                       )
'Insert into Barrios(id_barrio, nombre) Values (75 , 'BH_CAMINO A 60 CUADRAS'                        )
'Insert into Barrios(id_barrio, nombre) Values (76 , 'BIALET MASSE'                                  )
'Insert into Barrios(id_barrio, nombre) Values (77 , 'BOEDO'                                         )
'Insert into Barrios(id_barrio, nombre) Values (78 , 'BRIGADIER SAN MARTIN'                          )
'Insert into Barrios(id_barrio, nombre) Values (79 , 'CABANA DEL PILAR'                              )
'Insert into Barrios(id_barrio, nombre) Values (80 , 'CABO FARINA'                                   )
'Insert into Barrios(id_barrio, nombre) Values (81 , 'CACERES'                                       )
'Insert into Barrios(id_barrio, nombre) Values (82 , 'CALIFORNIA'                                    )
'Insert into Barrios(id_barrio, nombre) Values (83 , 'CAMINO A SAN CARLOS'                           )
'Insert into Barrios(id_barrio, nombre) Values (84 , 'CAMINO A VILLA POSSE'                          )
'Insert into Barrios(id_barrio, nombre) Values (85 , 'CARBO'                                         )
'Insert into Barrios(id_barrio, nombre) Values (86 , 'CAROLA LORENZINI'                              )
'Insert into Barrios(id_barrio, nombre) Values (87 , 'CARRARA'                                       )
'Insert into Barrios(id_barrio, nombre) Values (88 , 'CASEROS'                                       )
'Insert into Barrios(id_barrio, nombre) Values (89 , 'CENTRO'                                        )
'Insert into Barrios(id_barrio, nombre) Values (90 , 'CENTRO AMERICA'                                )
'Insert into Barrios(id_barrio, nombre) Values (91 , 'CERRO CHICO'                                   )
'Insert into Barrios(id_barrio, nombre) Values (92 , 'CERRO DE LAS ROSAS'                            )
'Insert into Barrios(id_barrio, nombre) Values (93 , 'CERRO NORTE'                                   )
'Insert into Barrios(id_barrio, nombre) Values (94 , 'CERVECEROS'                                    )
'Insert into Barrios(id_barrio, nombre) Values (95 , 'CHATEAU CARRERAS'                              )
'Insert into Barrios(id_barrio, nombre) Values (97 , 'CIUDAD AMPLIACION CABILDO'                     )
'Insert into Barrios(id_barrio, nombre) Values (98 , 'CIUDAD DE JUAN PABLO II'                       )
'Insert into Barrios(id_barrio, nombre) Values (99 , 'CIUDAD DE LOS CUARTETOS'                       )
'Insert into Barrios(id_barrio, nombre) Values (100, 'CIUDAD DE MIS SUENOS'                          )
'Insert into Barrios(id_barrio, nombre) Values (101, 'CIUDAD EVITA'                                  )
'Insert into Barrios(id_barrio, nombre) Values (102, 'CIUDAD MI ESPERANZA'                           )
'Insert into Barrios(id_barrio, nombre) Values (103, 'CIUDAD OBISPO ANGELELLI'                       )
'Insert into Barrios(id_barrio, nombre) Values (104, 'CIUDAD PARQUE LAS ROSAS'                       )
'Insert into Barrios(id_barrio, nombre) Values (105, 'CIUDAD VILLA RETIRO'                           )
'Insert into Barrios(id_barrio, nombre) Values (106, 'CIUDADELA'                                     )
'Insert into Barrios(id_barrio, nombre) Values (107, 'CLAROS DEL BOSQUE'                             )
'Insert into Barrios(id_barrio, nombre) Values (108, 'COFICO'                                        )
'Insert into Barrios(id_barrio, nombre) Values (109, 'COLINAS DE BELLA VISTA'                        )
'Insert into Barrios(id_barrio, nombre) Values (110, 'COLINAS DE VELEZ SARSFIELD'                    )
'Insert into Barrios(id_barrio, nombre) Values (111, 'COLINAS DEL CERRO'                             )
'Insert into Barrios(id_barrio, nombre) Values (112, 'COLON'                                         )
'Insert into Barrios(id_barrio, nombre) Values (113, 'COLONIA LOLA'                                  )
'Insert into Barrios(id_barrio, nombre) Values (114, 'COMANDANTE ESPORA'                             )
'Insert into Barrios(id_barrio, nombre) Values (115, 'COMERCIAL'                                     )
'Insert into Barrios(id_barrio, nombre) Values (116, 'CONGRESO'                                      )
'Insert into Barrios(id_barrio, nombre) Values (117, 'CONSORCIO 16 DE NOVIEMBRE'                     )
'Insert into Barrios(id_barrio, nombre) Values (118, 'CONSORCIO ESPERANZA'                           )
'Insert into Barrios(id_barrio, nombre) Values (119, 'COOPERATIVA 16 DE NOVIEMBRE'                   )
'Insert into Barrios(id_barrio, nombre) Values (120, 'COOPERATIVA EL FUTURO'                         )
'Insert into Barrios(id_barrio, nombre) Values (121, 'COOPERATIVA LA HERMOSA'                        )
'Insert into Barrios(id_barrio, nombre) Values (122, 'COOPERATIVA LA UNIDAD'                         )
'Insert into Barrios(id_barrio, nombre) Values (123, 'CORDOBA IV'                                    )
'Insert into Barrios(id_barrio, nombre) Values (124, 'CORDOBA V'                                     )
'Insert into Barrios(id_barrio, nombre) Values (125, 'CORRAL DE PALOS'                               )
'Insert into Barrios(id_barrio, nombre) Values (126, 'COSTA VERDE'                                   )
'Insert into Barrios(id_barrio, nombre) Values (127, 'COUNTRY ALTOS DEL CHATEAU'                     )
'Insert into Barrios(id_barrio, nombre) Values (128, 'COUNTRY BARRANCAS'                             )
'Insert into Barrios(id_barrio, nombre) Values (130, 'COUNTRY CLUB'                                  )
'Insert into Barrios(id_barrio, nombre) Values (131, 'COUNTRY FORTIN DEL POZO'                       )
'Insert into Barrios(id_barrio, nombre) Values (132, 'COUNTRY JOCKEY CLUB'                           )
'Insert into Barrios(id_barrio, nombre) Values (133, 'COUNTRY LA RESERVA'                            )
'Insert into Barrios(id_barrio, nombre) Values (134, 'COUNTRY LA SANTINA - COUNTRY CAMPIÐA DEL SUR'  )
'Insert into Barrios(id_barrio, nombre) Values (135, 'COUNTRY LAS DELICIAS'                          )
'Insert into Barrios(id_barrio, nombre) Values (136, 'COUNTRY LOMAS DE LA CAROLINA'                  )
'Insert into Barrios(id_barrio, nombre) Values (137, 'COUNTRY LOS ALGARROBOS'                        )
'Insert into Barrios(id_barrio, nombre) Values (138, 'COUNTRY LOS MIMBRES'                           )
'Insert into Barrios(id_barrio, nombre) Values (139, 'COUNTRY RANCH CLUB'                            )
'Insert into Barrios(id_barrio, nombre) Values (140, 'COUNTRY VALLE ESCONDIDO'                       )
'Insert into Barrios(id_barrio, nombre) Values (141, 'CRISOL NORTE'                                  )
'Insert into Barrios(id_barrio, nombre) Values (142, 'CRISOL SUD'                                    )
'Insert into Barrios(id_barrio, nombre) Values (143, 'CUPANI'                                        )
'Insert into Barrios(id_barrio, nombre) Values (144, 'DE LOS BIOQUIMICOS'                            )
'Insert into Barrios(id_barrio, nombre) Values (145, 'DE LOS DOCENTES'                               )
'Insert into Barrios(id_barrio, nombre) Values (146, 'DEAN FUNES'                                    )
'Insert into Barrios(id_barrio, nombre) Values (147, 'DUCASSE'                                       )
'Insert into Barrios(id_barrio, nombre) Values (148, 'EJERCITO ARGENTINO'                            )
'Insert into Barrios(id_barrio, nombre) Values (149, 'EL BOSQUE'                                     )
'Insert into Barrios(id_barrio, nombre) Values (150, 'EL CABILDO'                                    )
'Insert into Barrios(id_barrio, nombre) Values (151, 'EL CERRITO'                                    )
'Insert into Barrios(id_barrio, nombre) Values (152, 'EL PUEBLITO'                                   )
'Insert into Barrios(id_barrio, nombre) Values (153, 'EL QUEBRACHAL'                                 )
'Insert into Barrios(id_barrio, nombre) Values (154, 'EL QUEBRACHO'                                  )
'Insert into Barrios(id_barrio, nombre) Values (155, 'EL REFUGIO'                                    )
'Insert into Barrios(id_barrio, nombre) Values (156, 'EL TREBOL'                                     )
'Insert into Barrios(id_barrio, nombre) Values (157, 'EL VIEJO ALGARROBO'                            )
'Insert into Barrios(id_barrio, nombre) Values (158, 'EMAUS'                                         )
'Insert into Barrios(id_barrio, nombre) Values (159, 'EMPALME'                                       )
'Insert into Barrios(id_barrio, nombre) Values (160, 'EMPALME CASAS DE OBREROS Y EMPLEADOS'          )
'Insert into Barrios(id_barrio, nombre) Values (161, 'ESCOBAR'                                       )
'Insert into Barrios(id_barrio, nombre) Values (162, 'ESTACION FLORES'                               )
'Insert into Barrios(id_barrio, nombre) Values (163, 'FERRER'                                        )
'Insert into Barrios(id_barrio, nombre) Values (164, 'FERREYRA'                                      )
'Insert into Barrios(id_barrio, nombre) Values (165, 'FERREYRA SEGUNDA SECCION'                      )
'Insert into Barrios(id_barrio, nombre) Values (166, 'FERROVIARIO MITRE'                             )
'Insert into Barrios(id_barrio, nombre) Values (167, 'FINCA LA DOROTEA'                              )
'Insert into Barrios(id_barrio, nombre) Values (168, 'FINCAS DEL SUR'                                )
'Insert into Barrios(id_barrio, nombre) Values (169, 'GENERAL ARENALES'                              )
'Insert into Barrios(id_barrio, nombre) Values (170, 'GENERAL ARTIGAS'                               )
'Insert into Barrios(id_barrio, nombre) Values (171, 'GENERAL BELGRANO'                              )
'Insert into Barrios(id_barrio, nombre) Values (172, 'GENERAL BUSTOS'                                )
'Insert into Barrios(id_barrio, nombre) Values (173, 'GENERAL MOSCONI'                               )
'Insert into Barrios(id_barrio, nombre) Values (174, 'GENERAL PAZ'                                   )
'Insert into Barrios(id_barrio, nombre) Values (175, 'GENERAL PUEYRREDON'                            )
'Insert into Barrios(id_barrio, nombre) Values (176, 'GENERAL SAVIO'                                 )
'Insert into Barrios(id_barrio, nombre) Values (177, 'GRANADERO PRINGLES'                            )
'Insert into Barrios(id_barrio, nombre) Values (178, 'GRANJA DE FUNES'                               )
'Insert into Barrios(id_barrio, nombre) Values (180, 'GUARNICION MILITAR CORDOBA'                    )
'Insert into Barrios(id_barrio, nombre) Values (181, 'GUAYAQUIL'                                     )
'Insert into Barrios(id_barrio, nombre) Values (182, 'GUEMES'                                        )
'Insert into Barrios(id_barrio, nombre) Values (184, 'GUINAZU'                                       )
'Insert into Barrios(id_barrio, nombre) Values (185, 'GUINAZU SUD'                                   )
'Insert into Barrios(id_barrio, nombre) Values (186, 'HIPOLITO IRIGOYEN'                             )
'Insert into Barrios(id_barrio, nombre) Values (187, 'HOGAR PROPIO'                                  )
'Insert into Barrios(id_barrio, nombre) Values (188, 'HORIZONTE'                                     )
'Insert into Barrios(id_barrio, nombre) Values (189, 'INAUDI'                                        )
'Insert into Barrios(id_barrio, nombre) Values (190, 'INDEPENDENCIA'                                 )
'Insert into Barrios(id_barrio, nombre) Values (191, 'INDUSTRIAL ESTE'                               )
'Insert into Barrios(id_barrio, nombre) Values (192, 'INDUSTRIAL OESTE'                              )
'Insert into Barrios(id_barrio, nombre) Values (193, 'IPONA'                                         )
'Insert into Barrios(id_barrio, nombre) Values (194, 'IPV ANEXO LOS GIGANTES'                        )
'Insert into Barrios(id_barrio, nombre) Values (195, 'IRUPE'                                         )
'Insert into Barrios(id_barrio, nombre) Values (196, 'ITUZAINGO'                                     )
'Insert into Barrios(id_barrio, nombre) Values (197, 'ITUZAINGO ANEXO'                               )
'Insert into Barrios(id_barrio, nombre) Values (198, 'ITUZAINGO II'                                  )
'Insert into Barrios(id_barrio, nombre) Values (199, 'JARDIN'                                        )
'Insert into Barrios(id_barrio, nombre) Values (200, 'JARDIN DEL CLARET'                             )
'Insert into Barrios(id_barrio, nombre) Values (201, 'JARDIN DEL PILAR'                              )
'Insert into Barrios(id_barrio, nombre) Values (202, 'JARDIN DEL SUD'                                )
'Insert into Barrios(id_barrio, nombre) Values (203, 'JARDIN ESPINOSA'                               )
'Insert into Barrios(id_barrio, nombre) Values (204, 'JARDIN HIPODROMO'                              )
'Insert into Barrios(id_barrio, nombre) Values (205, 'JARDINES DEL JOCKEY'                           )
'Insert into Barrios(id_barrio, nombre) Values (206, 'JERONIMO LUIS DE CABRERA'                      )
'Insert into Barrios(id_barrio, nombre) Values (207, 'JOCKEY CLUB'                                   )
'Insert into Barrios(id_barrio, nombre) Values (208, 'JOSE HERNANDEZ'                                )
'Insert into Barrios(id_barrio, nombre) Values (209, 'JOSE I RUCCI'                                  )
'Insert into Barrios(id_barrio, nombre) Values (211, 'JOSE IGNACIO DIAZ SECCION 1'                   )
'Insert into Barrios(id_barrio, nombre) Values (212, 'JOSE IGNACIO DIAZ SECCION 2'                   )
'Insert into Barrios(id_barrio, nombre) Values (213, 'JOSE IGNACIO DIAZ SECCION 3'                   )
'Insert into Barrios(id_barrio, nombre) Values (214, 'JUAN B JUSTO'                                  )
'Insert into Barrios(id_barrio, nombre) Values (215, 'JUAN XXIII'                                    )
'Insert into Barrios(id_barrio, nombre) Values (216, 'JUNIORS'                                       )
'Insert into Barrios(id_barrio, nombre) Values (217, 'KAIROS'                                        )
'Insert into Barrios(id_barrio, nombre) Values (218, 'KENNEDY'                                       )
'Insert into Barrios(id_barrio, nombre) Values (219, 'LA CAROLINA'                                   )
'Insert into Barrios(id_barrio, nombre) Values (220, 'LA DOROTEA'                                    )
'Insert into Barrios(id_barrio, nombre) Values (221, 'LA ESPERANZA'                                  )
'Insert into Barrios(id_barrio, nombre) Values (222, 'LA FLORESTA'                                   )
'Insert into Barrios(id_barrio, nombre) Values (223, 'LA FRANCE'                                     )
'Insert into Barrios(id_barrio, nombre) Values (224, 'LA FRATERNIDAD'                                )
'Insert into Barrios(id_barrio, nombre) Values (225, 'LA HORTENSIA'                                  )
'Insert into Barrios(id_barrio, nombre) Values (226, 'LA SALLE'                                      )
'Insert into Barrios(id_barrio, nombre) Values (227, 'LA TOMA'                                       )
'Insert into Barrios(id_barrio, nombre) Values (228, 'LAMADRID'                                      )
'Insert into Barrios(id_barrio, nombre) Values (229, 'LAS CANITAS'                                   )
'Insert into Barrios(id_barrio, nombre) Values (230, 'LAS CANUELAS'                                  )
'Insert into Barrios(id_barrio, nombre) Values (231, 'LAS CORTADERAS'                                )
'Insert into Barrios(id_barrio, nombre) Values (232, 'LAS DALIAS'                                    )
'Insert into Barrios(id_barrio, nombre) Values (233, 'LAS FLORES'                                    )
'Insert into Barrios(id_barrio, nombre) Values (234, 'LAS HUERTILLAS'                                )
'Insert into Barrios(id_barrio, nombre) Values (235, 'LAS LILAS'                                     )
'Insert into Barrios(id_barrio, nombre) Values (236, 'LAS MAGNOLIAS'                                 )
'Insert into Barrios(id_barrio, nombre) Values (237, 'LAS MARGARITAS'                                )
'Insert into Barrios(id_barrio, nombre) Values (238, 'LAS PALMAS'                                    )
'Insert into Barrios(id_barrio, nombre) Values (239, 'LAS PALMAS ANEXO'                              )
'Insert into Barrios(id_barrio, nombre) Values (240, 'LAS PLAYAS'                                    )
'Insert into Barrios(id_barrio, nombre) Values (241, 'LAS ROSAS'                                     )
'Insert into Barrios(id_barrio, nombre) Values (242, 'LAS VIOLETAS'                                  )
'Insert into Barrios(id_barrio, nombre) Values (243, 'LICEO GENERAL PAZ'                             )
'Insert into Barrios(id_barrio, nombre) Values (244, 'LOMAS DE SAN MARTIN'                           )
'Insert into Barrios(id_barrio, nombre) Values (245, 'LOS ALAMOS'                                    )
'Insert into Barrios(id_barrio, nombre) Values (246, 'LOS ANGELES'                                   )
'Insert into Barrios(id_barrio, nombre) Values (247, 'LOS BOULEVARES'                                )
'Insert into Barrios(id_barrio, nombre) Values (248, 'LOS CEIBOS'                                    )
'Insert into Barrios(id_barrio, nombre) Values (249, 'LOS CHINGOLOS'                                 )
'Insert into Barrios(id_barrio, nombre) Values (250, 'LOS EUCALIPTUS'                                )
'Insert into Barrios(id_barrio, nombre) Values (251, 'LOS FILTROS'                                   )
'Insert into Barrios(id_barrio, nombre) Values (252, 'LOS FRESNOS'                                   )
'Insert into Barrios(id_barrio, nombre) Values (253, 'LOS GIGANTES'                                  )
'Insert into Barrios(id_barrio, nombre) Values (254, 'LOS GRANADOS'                                  )
'Insert into Barrios(id_barrio, nombre) Values (255, 'LOS HORNILLOS'                                 )
'Insert into Barrios(id_barrio, nombre) Values (256, 'LOS JACARANDAES'                               )
'Insert into Barrios(id_barrio, nombre) Values (257, 'LOS JOSEFINOS'                                 )
'Insert into Barrios(id_barrio, nombre) Values (258, 'LOS NARANJOS'                                  )
'Insert into Barrios(id_barrio, nombre) Values (259, 'LOS OLMOS'                                     )
'Insert into Barrios(id_barrio, nombre) Values (260, 'LOS OLMOS SUD'                                 )
'Insert into Barrios(id_barrio, nombre) Values (261, 'LOS PARAISOS'                                  )
'Insert into Barrios(id_barrio, nombre) Values (262, 'LOS PINOS'                                     )
'Insert into Barrios(id_barrio, nombre) Values (263, 'LOS PLATANOS'                                  )
'Insert into Barrios(id_barrio, nombre) Values (264, 'LOS ROBLES'                                    )
'Insert into Barrios(id_barrio, nombre) Values (265, 'LOS SAUCES'                                    )
'Insert into Barrios(id_barrio, nombre) Values (266, 'LOURDES'                                       )
'Insert into Barrios(id_barrio, nombre) Values (267, 'MAIPU SECCION 1'                               )
'Insert into Barrios(id_barrio, nombre) Values (268, 'MAIPU SECCION 2'                               )
'Insert into Barrios(id_barrio, nombre) Values (269, 'MALDONADO'                                     )
'Insert into Barrios(id_barrio, nombre) Values (484, 'MANATIALES I - MANATIALES II'                  )
'Insert into Barrios(id_barrio, nombre) Values (270, 'MARCELO T DE ALVEAR'                           )
'Insert into Barrios(id_barrio, nombre) Values (271, 'MARCOS SASTRE'                                 )
'Insert into Barrios(id_barrio, nombre) Values (272, 'MARECHAL'                                      )
'Insert into Barrios(id_barrio, nombre) Values (273, 'MARIA LASTENIA'                                )
'Insert into Barrios(id_barrio, nombre) Values (274, 'MARIANO BALCARCE'                              )
'Insert into Barrios(id_barrio, nombre) Values (275, 'MARIANO FRAGUEIRO'                             )
'Insert into Barrios(id_barrio, nombre) Values (276, 'MARQUES ANEXO'                                 )
'Insert into Barrios(id_barrio, nombre) Values (277, 'MARQUES DE SOBREMONTE'                         )
'Insert into Barrios(id_barrio, nombre) Values (278, 'MAULLER'                                       )
'Insert into Barrios(id_barrio, nombre) Values (279, 'MAURIZI'                                       )
'Insert into Barrios(id_barrio, nombre) Values (280, 'MERCANTIL'                                     )
'Insert into Barrios(id_barrio, nombre) Values (281, 'MILITAR GENERAL DEHEZA'                        )
'Insert into Barrios(id_barrio, nombre) Values (282, 'MIRADOR'                                       )
'Insert into Barrios(id_barrio, nombre) Values (283, 'MIRADOR DEL CHATEAU'                           )
'Insert into Barrios(id_barrio, nombre) Values (284, 'MIRALTA'                                       )
'Insert into Barrios(id_barrio, nombre) Values (285, 'MIRIZZI'                                       )
'Insert into Barrios(id_barrio, nombre) Values (286, 'MUTUAL DE LOS DOCENTES'                        )
'Insert into Barrios(id_barrio, nombre) Values (287, 'NICOLAS AVELLANEDA'                            )
'Insert into Barrios(id_barrio, nombre) Values (288, 'NUESTRO HOGAR I'                               )
'Insert into Barrios(id_barrio, nombre) Values (289, 'NUESTRO HOGAR II'                              )
'Insert into Barrios(id_barrio, nombre) Values (290, 'NUESTRO HOGAR III'                             )
'Insert into Barrios(id_barrio, nombre) Values (291, 'NUEVA CORDOBA'                                 )
'Insert into Barrios(id_barrio, nombre) Values (292, 'NUEVA CORDOBA ANEXA'                           )
'Insert into Barrios(id_barrio, nombre) Values (293, 'NUEVA ITALIA'                                  )
'Insert into Barrios(id_barrio, nombre) Values (294, 'NUEVO URCA'                                    )
'Insert into Barrios(id_barrio, nombre) Values (295, 'OBRERO'                                        )
'Insert into Barrios(id_barrio, nombre) Values (296, 'OBSERVATORIO'                                  )
'Insert into Barrios(id_barrio, nombre) Values (297, 'OMBU'                                          )
'Insert into Barrios(id_barrio, nombre) Values (298, 'ONA'                                           )
'Insert into Barrios(id_barrio, nombre) Values (299, 'OSN'                                           )
'Insert into Barrios(id_barrio, nombre) Values (300, 'PADRE CLARET'                                  )
'Insert into Barrios(id_barrio, nombre) Values (301, 'PALERMO BAJO'                                  )
'Insert into Barrios(id_barrio, nombre) Values (302, 'PALMAR'                                        )
'Insert into Barrios(id_barrio, nombre) Values (303, 'PALMAS DEL CLARET'                             )
'Insert into Barrios(id_barrio, nombre) Values (304, 'PANAMERICANO'                                  )
'Insert into Barrios(id_barrio, nombre) Values (305, 'PARQUE ALAMEDA'                                )
'Insert into Barrios(id_barrio, nombre) Values (306, 'PARQUE ATLANTICA'                              )
'Insert into Barrios(id_barrio, nombre) Values (307, 'PARQUE CAPITAL'                                )
'Insert into Barrios(id_barrio, nombre) Values (308, 'PARQUE CAPITAL SUD'                            )
'Insert into Barrios(id_barrio, nombre) Values (309, 'PARQUE CHACABUCO'                              )
'Insert into Barrios(id_barrio, nombre) Values (310, 'PARQUE CHATEAU CARRERAS'                       )
'Insert into Barrios(id_barrio, nombre) Values (311, 'PARQUE COREMA'                                 )
'Insert into Barrios(id_barrio, nombre) Values (312, 'PARQUE DE LA VEGA II'                          )
'Insert into Barrios(id_barrio, nombre) Values (313, 'PARQUE DE LA VEGA III'                         )
'Insert into Barrios(id_barrio, nombre) Values (314, 'PARQUE DEL ESTE'                               )
'Insert into Barrios(id_barrio, nombre) Values (315, 'PARQUE DON BOSCO'                              )
'Insert into Barrios(id_barrio, nombre) Values (316, 'PARQUE FUTURA'                                 )
'Insert into Barrios(id_barrio, nombre) Values (317, 'PARQUE JORGE NEWBERY'                          )
'Insert into Barrios(id_barrio, nombre) Values (318, 'PARQUE LATINO'                                 )
'Insert into Barrios(id_barrio, nombre) Values (319, 'PARQUE LICEO SECCION 1'                        )
'Insert into Barrios(id_barrio, nombre) Values (320, 'PARQUE LICEO SECCION 2'                        )
'Insert into Barrios(id_barrio, nombre) Values (321, 'PARQUE LICEO SECCION 3'                        )
'Insert into Barrios(id_barrio, nombre) Values (322, 'PARQUE LOS MOLINOS'                            )
'Insert into Barrios(id_barrio, nombre) Values (323, 'PARQUE MODELO'                                 )
'Insert into Barrios(id_barrio, nombre) Values (324, 'PARQUE MONTECRISTO'                            )
'Insert into Barrios(id_barrio, nombre) Values (325, 'PARQUE REPUBLICA'                              )
'Insert into Barrios(id_barrio, nombre) Values (326, 'PARQUE SAN CARLOS'                             )
'Insert into Barrios(id_barrio, nombre) Values (327, 'PARQUE SAN VICENTE'                            )
'Insert into Barrios(id_barrio, nombre) Values (328, 'PARQUE TABLADA'                                )
'Insert into Barrios(id_barrio, nombre) Values (329, 'PARQUE VELEZ SARSFIELD'                        )
'Insert into Barrios(id_barrio, nombre) Values (330, 'PASO DE LOS ANDES'                             )
'Insert into Barrios(id_barrio, nombre) Values (331, 'PATRIA'                                        )
'Insert into Barrios(id_barrio, nombre) Values (332, 'PATRICIOS'                                     )
'Insert into Barrios(id_barrio, nombre) Values (333, 'PATRICIOS ESTE'                                )
'Insert into Barrios(id_barrio, nombre) Values (334, 'PATRICIOS NORTE'                               )
'Insert into Barrios(id_barrio, nombre) Values (335, 'PATRICIOS OESTE'                               )
'Insert into Barrios(id_barrio, nombre) Values (336, 'PIEDRAS BLANCAS'                               )
'Insert into Barrios(id_barrio, nombre) Values (337, 'POETA LUGONES'                                 )
'Insert into Barrios(id_barrio, nombre) Values (338, 'POLICARPIO CABRAL'                             )
'Insert into Barrios(id_barrio, nombre) Values (339, 'POLICIAL'                                      )
'Insert into Barrios(id_barrio, nombre) Values (340, 'PORTAL DE CORDOBA'                             )
'Insert into Barrios(id_barrio, nombre) Values (341, 'PORTAL DEL JACARANDA'                          )
'Insert into Barrios(id_barrio, nombre) Values (342, 'POSTA DE VARGAS'                               )
'Insert into Barrios(id_barrio, nombre) Values (343, 'PRIMERA JUNTA'                                 )
'Insert into Barrios(id_barrio, nombre) Values (344, 'PROVIDENCIA'                                   )
'Insert into Barrios(id_barrio, nombre) Values (345, 'PUENTE BLANCO'                                 )
'Insert into Barrios(id_barrio, nombre) Values (346, 'QUEBRADA DE LAS ROSAS'                         )
'Insert into Barrios(id_barrio, nombre) Values (347, 'QUINTA SANTA ANA'                              )
'Insert into Barrios(id_barrio, nombre) Values (348, 'QUINTAS DE ARGUELLO'                           )
'Insert into Barrios(id_barrio, nombre) Values (349, 'QUINTAS DE FLORES'                             )
'Insert into Barrios(id_barrio, nombre) Values (350, 'QUINTAS DE ITALIA'                             )
'Insert into Barrios(id_barrio, nombre) Values (351, 'QUINTAS DE SAN JORGE'                          )
'Insert into Barrios(id_barrio, nombre) Values (352, 'RAMON J CARCANO'                               )
'Insert into Barrios(id_barrio, nombre) Values (353, 'RECREO DEL NORTE'                              )
'Insert into Barrios(id_barrio, nombre) Values (354, 'REMEDIOS DE ESCALADA'                          )
'Insert into Barrios(id_barrio, nombre) Values (355, 'RENACIMIENTO'                                  )
'Insert into Barrios(id_barrio, nombre) Values (356, 'RENE FAVALORO'                                 )
'Insert into Barrios(id_barrio, nombre) Values (357, 'RENE FAVALORO II'                              )
'Insert into Barrios(id_barrio, nombre) Values (358, 'RES CHATEAU CARRERAS CO VI CO'                 )
'Insert into Barrios(id_barrio, nombre) Values (359, 'RESIDENCIAL AMERICA'                           )
'Insert into Barrios(id_barrio, nombre) Values (360, 'RESIDENCIAL ARAGON'                            )
'Insert into Barrios(id_barrio, nombre) Values (361, 'RESIDENCIAL OLIVOS'                            )
'Insert into Barrios(id_barrio, nombre) Values (362, 'RESIDENCIAL SAN CARLOS'                        )
'Insert into Barrios(id_barrio, nombre) Values (363, 'RESIDENCIAL SAN JORGE'                         )
'Insert into Barrios(id_barrio, nombre) Values (364, 'RESIDENCIAL SAN ROQUE'                         )
'Insert into Barrios(id_barrio, nombre) Values (365, 'RESIDENCIAL SANTA ANA'                         )
'Insert into Barrios(id_barrio, nombre) Values (366, 'RESIDENCIAL SANTA ROSA'                        )
'Insert into Barrios(id_barrio, nombre) Values (367, 'RESIDENCIAL SUD'                               )
'Insert into Barrios(id_barrio, nombre) Values (368, 'RESIDENCIAL VELEZ SARSFIELD'                   )
'Insert into Barrios(id_barrio, nombre) Values (369, 'RIVADAVIA'                                     )
'Insert into Barrios(id_barrio, nombre) Values (370, 'RIVERA INDARTE'                                )
'Insert into Barrios(id_barrio, nombre) Values (372, 'ROGELIO MARTINEZ'                              )
'Insert into Barrios(id_barrio, nombre) Values (373, 'ROSEDAL'                                       )
'Insert into Barrios(id_barrio, nombre) Values (374, 'ROSEDAL ANEXO'                                 )
'Insert into Barrios(id_barrio, nombre) Values (375, 'SACHI'                                         )
'Insert into Barrios(id_barrio, nombre) Values (376, 'SAN ANTONIO'                                   )
'Insert into Barrios(id_barrio, nombre) Values (377, 'SAN CAYETANO'                                  )
'Insert into Barrios(id_barrio, nombre) Values (378, 'SAN DANIEL'                                    )
'Insert into Barrios(id_barrio, nombre) Values (379, 'SAN FELIPE'                                    )
'Insert into Barrios(id_barrio, nombre) Values (380, 'SAN FERNANDO'                                  )
'Insert into Barrios(id_barrio, nombre) Values (381, 'SAN FRANCISCO'                                 )
'Insert into Barrios(id_barrio, nombre) Values (382, 'SAN IGNACIO'                                   )
'Insert into Barrios(id_barrio, nombre) Values (383, 'SAN JAVIER'                                    )
'Insert into Barrios(id_barrio, nombre) Values (384, 'SAN JOSE'                                      )
'Insert into Barrios(id_barrio, nombre) Values (385, 'SAN LORENZO'                                   )
'Insert into Barrios(id_barrio, nombre) Values (386, 'SAN LORENZO NORTE'                             )
'Insert into Barrios(id_barrio, nombre) Values (387, 'SAN LUIS DE FRANCIA'                           )
'Insert into Barrios(id_barrio, nombre) Values (388, 'SAN MARCELO'                                   )
'Insert into Barrios(id_barrio, nombre) Values (389, 'SAN MARTIN'                                    )
'Insert into Barrios(id_barrio, nombre) Values (391, 'SAN MARTIN ANEXO'                              )
'Insert into Barrios(id_barrio, nombre) Values (392, 'SAN MARTIN NORTE'                              )
'Insert into Barrios(id_barrio, nombre) Values (393, 'SAN NICOLAS'                                   )
'Insert into Barrios(id_barrio, nombre) Values (394, 'SAN PABLO'                                     )
'Insert into Barrios(id_barrio, nombre) Values (395, 'SAN PEDRO NOLASCO'                             )
'Insert into Barrios(id_barrio, nombre) Values (396, 'SAN RAFAEL'                                    )
'Insert into Barrios(id_barrio, nombre) Values (397, 'SAN RAMON'                                     )
'Insert into Barrios(id_barrio, nombre) Values (398, 'SAN SALVADOR'                                  )
'Insert into Barrios(id_barrio, nombre) Values (399, 'SAN VICENTE'                                   )
'Insert into Barrios(id_barrio, nombre) Values (400, 'SANTA CECILIA'                                 )
'Insert into Barrios(id_barrio, nombre) Values (401, 'SANTA CLARA DE ASIS'                           )
'Insert into Barrios(id_barrio, nombre) Values (402, 'SANTA ISABEL ANEXO'                            )
'Insert into Barrios(id_barrio, nombre) Values (403, 'SANTA ISABEL SECCION 1'                        )
'Insert into Barrios(id_barrio, nombre) Values (404, 'SANTA ISABEL SECCION 2'                        )
'Insert into Barrios(id_barrio, nombre) Values (405, 'SANTA ISABEL SECCION 3'                        )
'Insert into Barrios(id_barrio, nombre) Values (406, 'SANTA RITA'                                    )
'Insert into Barrios(id_barrio, nombre) Values (407, 'SARGENTO CABRAL'                               )
'Insert into Barrios(id_barrio, nombre) Values (408, 'SARMIENTO'                                     )
'Insert into Barrios(id_barrio, nombre) Values (409, 'SEP'                                           )
'Insert into Barrios(id_barrio, nombre) Values (410, 'SEP SEGUNDA ETAPA'                             )
'Insert into Barrios(id_barrio, nombre) Values (411, 'SMATA'                                         )
'Insert into Barrios(id_barrio, nombre) Values (412, 'SOLARES DE SANTA MARIA - ALTOS DE MANANTIALES' )
'Insert into Barrios(id_barrio, nombre) Values (413, 'SUAREZ'                                        )
'Insert into Barrios(id_barrio, nombre) Values (414, 'TABLADA PARK'                                  )
'Insert into Barrios(id_barrio, nombre) Values (415, 'TALLERES ESTE'                                 )
'Insert into Barrios(id_barrio, nombre) Values (416, 'TALLERES OESTE'                                )
'Insert into Barrios(id_barrio, nombre) Values (417, 'TALLERES SUD'                                  )
'Insert into Barrios(id_barrio, nombre) Values (418, 'TEJAS DEL SUR'                                 )
'Insert into Barrios(id_barrio, nombre) Values (419, 'TEJAS II'                                      )
'Insert into Barrios(id_barrio, nombre) Values (420, 'TENIENTE BENJAMIN MATIENZO'                    )
'Insert into Barrios(id_barrio, nombre) Values (421, 'TEODORO FELDS'                                 )
'Insert into Barrios(id_barrio, nombre) Values (422, 'TRANVIARIOS'                                   )
'Insert into Barrios(id_barrio, nombre) Values (423, 'UOCRA'                                         )
'Insert into Barrios(id_barrio, nombre) Values (424, 'URCA'                                          )
'Insert into Barrios(id_barrio, nombre) Values (425, 'URITORCO'                                      )
'Insert into Barrios(id_barrio, nombre) Values (426, 'URQUIZA'                                       )
'Insert into Barrios(id_barrio, nombre) Values (427, 'VALLE DEL CERRO'                               )
'Insert into Barrios(id_barrio, nombre) Values (428, 'VASQUEZ'                                       )
'Insert into Barrios(id_barrio, nombre) Values (429, 'VICOR'                                         )
'Insert into Barrios(id_barrio, nombre) Values (430, 'VILLA 4 DE AGOSTO'                             )
'Insert into Barrios(id_barrio, nombre) Values (431, 'VILLA 9 DE JULIO'                              )
'Insert into Barrios(id_barrio, nombre) Values (432, 'VILLA ADELA'                                   )
'Insert into Barrios(id_barrio, nombre) Values (433, 'VILLA ALBERDI'                                 )
'Insert into Barrios(id_barrio, nombre) Values (434, 'VILLA ALBERTO'                                 )
'Insert into Barrios(id_barrio, nombre) Values (435, 'VILLA ALICIA RISLER'                           )
'Insert into Barrios(id_barrio, nombre) Values (436, 'VILLA ALLENDE PARQUE'                          )
'Insert into Barrios(id_barrio, nombre) Values (437, 'VILLA ARGENTINA'                               )
'Insert into Barrios(id_barrio, nombre) Values (438, 'VILLA ASPACIA'                                 )
'Insert into Barrios(id_barrio, nombre) Values (439, 'VILLA AVALOS'                                  )
'Insert into Barrios(id_barrio, nombre) Values (440, 'VILLA AZALAIS'                                 )
'Insert into Barrios(id_barrio, nombre) Values (441, 'VILLA AZALAIS ANEXO'                           )
'Insert into Barrios(id_barrio, nombre) Values (442, 'VILLA AZALAIS OESTE'                           )
'Insert into Barrios(id_barrio, nombre) Values (443, 'VILLA BELGRANO'                                )
'Insert into Barrios(id_barrio, nombre) Values (444, 'VILLA BUSTOS'                                  )
'Insert into Barrios(id_barrio, nombre) Values (445, 'VILLA CABRERA'                                 )
'Insert into Barrios(id_barrio, nombre) Values (446, 'VILLA CENTENARIO'                              )
'Insert into Barrios(id_barrio, nombre) Values (447, 'VILLA CLARET'                                  )
'Insert into Barrios(id_barrio, nombre) Values (448, 'VILLA CLAUDINA'                                )
'Insert into Barrios(id_barrio, nombre) Values (449, 'VILLA CORINA'                                  )
'Insert into Barrios(id_barrio, nombre) Values (450, 'VILLA CORNU'                                   )
'Insert into Barrios(id_barrio, nombre) Values (451, 'VILLA CORONEL OLMEDO'                          )
'Insert into Barrios(id_barrio, nombre) Values (452, 'VILLA EL LIBERTADOR'                           )
'Insert into Barrios(id_barrio, nombre) Values (453, 'VILLA ESQUIU'                                  )
'Insert into Barrios(id_barrio, nombre) Values (454, 'VILLA EUCARISTICA'                             )
'Insert into Barrios(id_barrio, nombre) Values (455, 'VILLA GENERAL URQUIZA'                         )
'Insert into Barrios(id_barrio, nombre) Values (456, 'VILLA GRAN PARQUE'                             )
'Insert into Barrios(id_barrio, nombre) Values (457, 'VILLA LA MERCED'                               )
'Insert into Barrios(id_barrio, nombre) Values (458, 'VILLA MAFEKIN'                                 )
'Insert into Barrios(id_barrio, nombre) Values (459, 'VILLA MARTA'                                   )
'Insert into Barrios(id_barrio, nombre) Values (460, 'VILLA MARTINEZ'                                )
'Insert into Barrios(id_barrio, nombre) Values (461, 'VILLA PAEZ'                                    )
'Insert into Barrios(id_barrio, nombre) Values (462, 'VILLA QUISQUIZACATE'                           )
'Insert into Barrios(id_barrio, nombre) Values (463, 'VILLA RETIRO'                                  )
'Insert into Barrios(id_barrio, nombre) Values (464, 'VILLA REVOL'                                   )
'Insert into Barrios(id_barrio, nombre) Values (465, 'VILLA REVOL ANEXO'                             )
'Insert into Barrios(id_barrio, nombre) Values (466, 'VILLA RIVADAVIA'                               )
'Insert into Barrios(id_barrio, nombre) Values (467, 'VILLA RIVERA INDARTE'                          )
'Insert into Barrios(id_barrio, nombre) Values (468, 'VILLA SAN CARLOS'                              )
'Insert into Barrios(id_barrio, nombre) Values (469, 'VILLA SAN ISIDRO'                              )
'Insert into Barrios(id_barrio, nombre) Values (470, 'VILLA SERRANA'                                 )
'Insert into Barrios(id_barrio, nombre) Values (471, 'VILLA SIBURU'                                  )
'Insert into Barrios(id_barrio, nombre) Values (472, 'VILLA SILVANO FUNES'                           )
'Insert into Barrios(id_barrio, nombre) Values (473, 'VILLA SOLFERINO'                               )
'Insert into Barrios(id_barrio, nombre) Values (474, 'VILLA UNION'                                   )
'Insert into Barrios(id_barrio, nombre) Values (475, 'VILLA WARCALDE'                                )
'Insert into Barrios(id_barrio, nombre) Values (477, 'VIVERO NORTE'                                  )
'Insert into Barrios(id_barrio, nombre) Values (478, 'YAPEYU'                                        )
'Insert into Barrios(id_barrio, nombre) Values (479, 'YOFRE H'                                       )
'Insert into Barrios(id_barrio, nombre) Values (480, 'YOFRE I'                                       )
'Insert into Barrios(id_barrio, nombre) Values (481, 'YOFRE NORTE'                                   )
'Insert into Barrios(id_barrio, nombre) Values (482, 'YOFRE SUD'                                     )
'Insert into Barrios(id_barrio, nombre) Values (483, 'ZEPA'                                          )


'INSERT INTO Razas_Perros(id_raza, nombre_raza) VALUES(	9	,'Boxer'              )
'INSERT INTO Razas_Perros(id_raza, nombre_raza) VALUES(	10	,'Dachshunds'         )
'INSERT INTO Razas_Perros(id_raza, nombre_raza) VALUES(	11	,'Rottweiler'         )
'INSERT INTO Razas_Perros(id_raza, nombre_raza) VALUES(	12	,'Pit Bull'           )
'INSERT INTO Razas_Perros(id_raza, nombre_raza) VALUES(	13	,'Chow Chow'          )
'INSERT INTO Razas_Perros(id_raza, nombre_raza) VALUES(	14	,'Dalmata'            )
'INSERT INTO Razas_Perros(id_raza, nombre_raza) VALUES(	15	,'Collie'             )
'INSERT INTO Razas_Perros(id_raza, nombre_raza) VALUES(	16	,'Pug Carlino'        )
'INSERT INTO Razas_Perros(id_raza, nombre_raza) VALUES(	17	,'Doberman'           )
'INSERT INTO Razas_Perros(id_raza, nombre_raza) VALUES(	18	,'Gran Danés'         )
'INSERT INTO Razas_Perros(id_raza, nombre_raza) VALUES(	19	,'Cocker Inglés'      )
'INSERT INTO Razas_Perros(id_raza, nombre_raza) VALUES(	20	,'Schnauzer'          )
'INSERT INTO Razas_Perros(id_raza, nombre_raza) VALUES(	21	,'Shar Pei'           )
'INSERT INTO Razas_Perros(id_raza, nombre_raza) VALUES(	22	,'Bichon Maltés'      )
'INSERT INTO Razas_Perros(id_raza, nombre_raza) VALUES(	23	,'Border Collie'      )
'INSERT INTO Razas_Perros(id_raza, nombre_raza) VALUES(	24	,'Chihuahua'          )
'INSERT INTO Razas_Perros(id_raza, nombre_raza) VALUES(	25	,'Bull Terrier'       )
'INSERT INTO Razas_Perros(id_raza, nombre_raza) VALUES(	26	,'Pastor Belga'       )
'INSERT INTO Razas_Perros(id_raza, nombre_raza) VALUES(	27	,'Basset Hound'       )
'INSERT INTO Razas_Perros(id_raza, nombre_raza) VALUES(	28	,'Cocker Americano'   )
'INSERT INTO Razas_Perros(id_raza, nombre_raza) VALUES(	29	,'Corgi'              )
'INSERT INTO Razas_Perros(id_raza, nombre_raza) VALUES(	30	,'Pincher'            )
'INSERT INTO Razas_Perros(id_raza, nombre_raza) VALUES(	31	,'Fox Terrier'        )
'INSERT INTO Razas_Perros(id_raza, nombre_raza) VALUES(	32	,'Mastín Napolitano'  )
'INSERT INTO Razas_Perros(id_raza, nombre_raza) VALUES(	33	,'Pekines'            )
'INSERT INTO Razas_Perros(id_raza, nombre_raza) VALUES(	34	,'Galgo'              )